In [6]:
import numpy as np

# Matrix 'A' in Ap=0

In [8]:
a = np.array(
[
    [20, 20, 80, 1, 0, 0, 0, 0, -484*20, -484*20, -484*8, -484],
    [0, 0, 0, 0, 20, 20, 80, 1, -471*20, -471*20, -471*8, -471],
    [60, 60, 80, 1, 0, 0, 0, 0, -606*60, -606*60, -606*80, -606],
    [0, 0, 0, 0, 60, 60, 80, 1, -354*60, -354*60, -354*80, -354],
    [80, 80, 80, 1, 0, 0, 0, 0, -668*80, -668*80, -668*80, -668],
    [0, 0, 0, 0, 80, 80, 80, 1, -289*80, -289*80, -289*80, -289],
    [100, 100, 80, 1, 0, 0, 0, 0, -731*100, -731*100, -731*80, -731],
    [0, 0, 0, 0, 100, 100, 80, 1, -229*100, -229*100, -229*80, -229],
    [120, 120, 80, 1, 0, 0, 0, 0, -791*120, -791*120, -791*80, -791],
    [0, 0, 0, 0, 120, 120, 80, 1, -164*120, -164*120, -164*80, -164],
    [150, 150, 80, 1, 0, 0, 0, 0, -885*150, -885*150, -885*80, -885],
    [0, 0, 0, 0, 150, 150, 80, 1, -73*150, -73*150, -73*80, -73]
    ])
a

array([[     20,      20,      80,       1,       0,       0,       0,
              0,   -9680,   -9680,   -3872,    -484],
       [      0,       0,       0,       0,      20,      20,      80,
              1,   -9420,   -9420,   -3768,    -471],
       [     60,      60,      80,       1,       0,       0,       0,
              0,  -36360,  -36360,  -48480,    -606],
       [      0,       0,       0,       0,      60,      60,      80,
              1,  -21240,  -21240,  -28320,    -354],
       [     80,      80,      80,       1,       0,       0,       0,
              0,  -53440,  -53440,  -53440,    -668],
       [      0,       0,       0,       0,      80,      80,      80,
              1,  -23120,  -23120,  -23120,    -289],
       [    100,     100,      80,       1,       0,       0,       0,
              0,  -73100,  -73100,  -58480,    -731],
       [      0,       0,       0,       0,     100,     100,      80,
              1,  -22900,  -22900,  -18320,    -229],


# Computing transpose of Matrix 'A'

In [9]:
at = a.transpose()
at

array([[     20,       0,      60,       0,      80,       0,     100,
              0,     120,       0,     150,       0],
       [     20,       0,      60,       0,      80,       0,     100,
              0,     120,       0,     150,       0],
       [     80,       0,      80,       0,      80,       0,      80,
              0,      80,       0,      80,       0],
       [      1,       0,       1,       0,       1,       0,       1,
              0,       1,       0,       1,       0],
       [      0,      20,       0,      60,       0,      80,       0,
            100,       0,     120,       0,     150],
       [      0,      20,       0,      60,       0,      80,       0,
            100,       0,     120,       0,     150],
       [      0,      80,       0,      80,       0,      80,       0,
             80,       0,      80,       0,      80],
       [      0,       1,       0,       1,       0,       1,       0,
              1,       0,       1,       0,       1],


# Multiplying the transpose of 'A' with 'A'

In [62]:
l = np.matmul(at, a)
l

array([[      57300,       57300,       42400,         530,           0,
                  0,           0,           0,   -45263300,   -45263300,
          -31323040,     -400250],
       [      57300,       57300,       42400,         530,           0,
                  0,           0,           0,   -45263300,   -45263300,
          -31323040,     -400250],
       [      42400,       42400,       38400,         480,           0,
                  0,           0,           0,   -32020000,   -32020000,
          -23868160,     -333200],
       [        530,         530,         480,           6,           0,
                  0,           0,           0,     -400250,     -400250,
            -298352,       -4165],
       [          0,           0,           0,           0,       57300,
              57300,       42400,         530,    -9606500,    -9606500,
           -7906560,     -107310],
       [          0,           0,           0,           0,       57300,
              57300,  

# Since the projection matrix is the Eigen vector with the smallest Eigen value of the matrix 'AT.A', we take the minimum value of each row in the above matrix. (AT.A)

In [63]:
l.min(axis=1)

array([  -45263300,   -45263300,   -32020000,     -400250,    -9606500,
          -9606500,    -8584800,     -107310,  -301117864,  -301117864,
       -1924174272,     -400250])

# Converting the 3x4 projection matrix by eliminating the last column since the remaining 3x3  matrix is the product of Intrinsic matrix and rotation matrix.

In [64]:
kp = np.array(
[
    [-45263300,   -45263300,   -32020000],
    [-9606500, -9606500,    -8584800],
    [-301117864,  -301117864, -1924174272]
])

# QR factorization of the 3x3 projection  matrix to split it into Intrinsic matrix and rotation matrix.

In [65]:
q, r = np.linalg.qr(kp)

## Rotation Matrix

In [68]:
q

array([[-1.48573640e-01,  9.88901136e-01,  6.44901894e-04],
       [-3.15326694e-02, -4.08569421e-03, -9.99494371e-01],
       [-9.88398485e-01, -1.48518852e-01,  3.17897190e-02]])

## Intrinsic Matrix

In [69]:
r

array([[ 3.04652292e+08,  3.04652292e+08,  1.90687896e+09],
       [ 0.00000000e+00,  5.96337415e-08,  2.54146615e+08],
       [ 0.00000000e+00,  0.00000000e+00, -5.26091499e+07]])

# The remaining elements of the 3x4 projection Matrix (p14, p24, p34)

In [72]:
pRem = np.array(
[
    [ -400250],
    [-107310],
    [-400250]
]
)

In [51]:
# k = np.array(
# [
#     [189626617.064498, -6308262.25313463, -18918110.723287497],
#     [0.0, 3210129.39079981108, 13246809.457622709],
#     [0.0, 0.0, -228859.833442002743932]
# ]
# )

# Now, computing translation matrix to get the Extrinsic Matrix, for that, we first compute the Translation vector

## We first calculate '~K'

In [52]:
kInverse = np.linalg.inv(r)
kInverse

array([[ 3.28243058e-09, -1.67690300e+07, -8.10085739e+07],
       [ 0.00000000e+00,  1.67690300e+07,  8.10085739e+07],
       [-0.00000000e+00, -0.00000000e+00, -1.90081003e-08]])

## Multiplying '~K' with pRem to get the Translation Vector

In [53]:
t = np.matmul(kInverse, pRem)
t

array([[ 3.42231663e+13],
       [-3.42231663e+13],
       [ 7.60799216e-03]])

# Computing Homography

### Adding the matrix 'A' as a numpy array

In [35]:
ah = np.array(
[
    [484, 471, 1, 0, 0, 0, -634*484, -634*471, -634],
    [0, 0, 0, 484, 471, 1, -610*484, -610*471, 610],
    [606, 354, 1, 0, 0, 0, -717*606, -717*354, -717],
    [0, 0, 0, 606, 354,1, -436*606, -463*354, -463],
    [668, 289, 1, 0, 0, 0, -759*668, -759*289, -759],
    [0, 0, 0, 668, 289, 1, -386*668, -386*289, -386],
    [731, 229, 1, 0, 0, 0, -804*731, -804*229, -804],
    [0, 0, 0, 731, 229, 1, -308*731, -308*229, -308],
    [791, 164, 1, 0, 0, 0, -843*791, -834*164, -843],
    [0, 0, 0, 791, 164, 1, -231*791, -231*164, -231],
    [885, 73, 1, 0, 0, 0, -908*885, -908*73, -908],
    [0, 0, 0, 885, 73, 1, -117*885, -117*73, -117]
]
)
ah

array([[    484,     471,       1,       0,       0,       0, -306856,
        -298614,    -634],
       [      0,       0,       0,     484,     471,       1, -295240,
        -287310,     610],
       [    606,     354,       1,       0,       0,       0, -434502,
        -253818,    -717],
       [      0,       0,       0,     606,     354,       1, -264216,
        -163902,    -463],
       [    668,     289,       1,       0,       0,       0, -507012,
        -219351,    -759],
       [      0,       0,       0,     668,     289,       1, -257848,
        -111554,    -386],
       [    731,     229,       1,       0,       0,       0, -587724,
        -184116,    -804],
       [      0,       0,       0,     731,     229,       1, -225148,
         -70532,    -308],
       [    791,     164,       1,       0,       0,       0, -666813,
        -136776,    -843],
       [      0,       0,       0,     791,     164,       1, -182721,
         -37884,    -231],
       [    885,    

In [36]:
aht = ah.transpose()
aht

array([[    484,       0,     606,       0,     668,       0,     731,
              0,     791,       0,     885,       0],
       [    471,       0,     354,       0,     289,       0,     229,
              0,     164,       0,      73,       0],
       [      1,       0,       1,       0,       1,       0,       1,
              0,       1,       0,       1,       0],
       [      0,     484,       0,     606,       0,     668,       0,
            731,       0,     791,       0,     885],
       [      0,     471,       0,     354,       0,     289,       0,
            229,       0,     164,       0,      73],
       [      0,       1,       0,       1,       0,       1,       0,
              1,       0,       1,       0,       1],
       [-306856, -295240, -434502, -264216, -507012, -257848, -587724,
        -225148, -666813, -182721, -803580, -103545],
       [-298614, -287310, -253818, -163902, -219351, -111554, -184116,
         -70532, -136776,  -37884,  -66284,   -8541],


In [38]:
lamb = np.matmul(aht, a)
lamb

array([[     400250,      400250,      333200,        4165,           0,
                  0,           0,           0,  -308418770,  -308418770,
         -222412208,    -2990983],
       [     107310,      107310,      126400,        1580,           0,
                  0,           0,           0,   -74872410,   -74872410,
          -63368032,     -997268],
       [        530,         530,         480,           6,           0,
                  0,           0,           0,     -400250,     -400250,
            -298352,       -4165],
       [          0,           0,           0,           0,      400250,
             400250,      333200,        4165,   -74872410,   -74872410,
          -63368032,     -997268],
       [          0,           0,           0,           0,      107310,
             107310,      126400,        1580,   -27908430,   -27908430,
          -25254968,     -515344],
       [          0,           0,           0,           0,         530,
                530,  

In [73]:
h = lamb.min(axis=1)

In [74]:
h

array([ -308418770,   -74872410,     -400250,   -74872410,   -27908430,
           -107310, -1668194496,  -688417536,     -434180])